apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: leader-example
  namespace: default
spec:
  holderIdentity: ""
  leaseDurationSeconds: 30
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: lease-manager-role
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-boot-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lease-manager-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: spring-boot-sa
  namespace: default
roleRef:
  kind: Role
  name: lease-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-example
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leader-example
  template:
    metadata:
      labels:
        app: leader-example
    spec:
      serviceAccountName: spring-boot-sa
      containers:
      - name: leader-example
        image: leader_example:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        env:
        - name: KUBERNETES_LEADER_ELECTION
          value: "true"
        - name: LEASE_NAME
          value: "leader-example"
        - name: LEASE_DURATION_SECONDS
          value: "30"
        - name: RENEW_DEADLINE_SECONDS
          value: "20"
        - name: RETRY_PERIOD_MILLIS
          value: "5000"
